---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - portfolio-item
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: modii-website
public_path: https://res.cloudinary.com/modii/w_1000,q_60,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: '0.49'
