---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - portfolio-item
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/clients
  label: Clients
  create: documents
  match: "**/*"
  templates:
  - client
- type: document
  path: data/settings.yaml
  label: Site Settings
upload_dir: modii-website
public_path: https://res.cloudinary.com/modii/w_1000,q_60,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.49
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
