---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - portfolio-item
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: modii-website
public_path: https://res.cloudinary.com/modii/w_1000,q_60,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.49
  preview_output_directory: public
  output_directory: public
version: '0.49'
